bind r source-file ~/.tmux.conf

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix


set -sg escape-time 0

set -g mouse on

# Start windows and panes index at 1, not 0.
set -g base-index 1
setw -g pane-base-index 1

# Ensure window index numbers get reordered on delete.
set-option -g renumber-windows on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @plugin 'dracula/tmux'
set -g @dracula-show-battery false
set -g @dracula-show-powerline true
set -g @dracula-refresh-rate 10

# Need to clone tpm
run '~/.tmux/plugins/tpm/tpm'

bind k run-shell "sesh-sessions"
